version: "3.3"

services:
  haproxy:
    image: zimbra/zm-x-client-proxy:20180426_1712
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    configs:
      - haproxy
      - ui_server
      - zimbra_server
    networks:
      zm-docker_default: {}
    secrets:
      - cert
    entrypoint:
      - /entrypoint
    ports:
      - "80:80"
      - "443:443"

configs:
  haproxy:
    file: ./haproxy.cfg
  zimbra_server:
    file: ./zimbra_server.cfg
  ui_server:
    file: ./ui_server.cfg

secrets:
  cert:
    file: ./server.pem

networks:
  zm-docker_default:
    external: true
