#!/bin/sh
# Entrypoint for lonni-alpine
CFG=/usr/local/etc/haproxy/haproxy.cfg
UI_SERVER=`cat /ui_server`
ZIMBRA_SERVER=`cat /zimbra_server`

echo "Install the haproxy config..."
cat /haproxy | sed -e "s/API_SERVER/$ZIMBRA_SERVER/g" -e "s/UI_SERVER/$UI_SERVER/g" > ${CFG}
chmod 777 ${CFG}

echo "Install the cert to /usr/local/etc/ssl/server.pem.."
cp /run/secrets/cert /usr/local/etc/ssl/server.pem
chmod 444 /usr/local/etc/ssl/server.pem

echo "Start rsyslogd..."
rsyslogd

echo "Start haproxy..."
haproxy -f ${CFG}

sleep 2
echo "SETUP COMPLETE"
tail -f /var/log/messages
