#!/bin/sh
# Entrypoint for lonni-alpine
CFG=/usr/local/etc/haproxy/haproxy.cfg

echo "Install the haproxy config..."
cp /haproxy ${CFG}
chmod 777 ${CFG}

echo "Install the cert to /usr/local/etc/ssl/server.pem.."
cp /run/secrets/cert /usr/local/etc/ssl/server.pem
chmod 444 /usr/local/etc/ssl/server.pem

echo "Start rsyslogd..."
rsyslogd

echo "Start haproxy..."
haproxy -f ${CFG}

